### ISSUE TITLE
what's the meaning of the label in your training data?

### ISSUE THREAD

**Issue by leolle** [changwookjun/Transformer#2]
I would like to construct some training data of my own, what if I just have only dialogues? thank you.

**Comment by ECNUHP** [comment]
> I would like to construct some training data of my own, what if I just have only dialogues? thank you.
 The label  is to indicate the positive and negative

**Comment by changwookjun** [comment]
The label is to indicate follows
0 : natural
1 : farewell
2 :  love

**Comment by leolle** [comment]
> The label is to indicate follows
> 0 : natural
> 1 : farewell
> 2 : love

thank you.
